use_frameworks!

target 'Disintegrate_Example' do
  pod 'Disintegrate', :path => '../'

  target 'Disintegrate_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
