use_frameworks!

target 'Disintegrate_Example' do
  pod 'Disintegrate', :path => '../'

  target 'Disintegrate_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
